### ISSUE TITLE
include svg in dist and make proper URLs to it or inline it to css

### ISSUE THREAD

**Issue by Guria** [bem/bem-components-dist#3]
using bem-components.css causes 404 errors: 
`GET https://domain.tld/libs/design/common.blocks/theme/_islands/tip.svg 404 (Not Found)`

**Comment by tadatuta** [comment]
@Guria images are already inlined in prod version and will be inlined in dev version after https://github.com/bem/bem-components/issues/1568

**Comment by tadatuta** [comment]
Fixed in https://github.com/bem/bem-components-dist/releases/tag/v2.3.0
