### ISSUE TITLE
Обновление версии

### ISSUE THREAD

**Issue by AR1ES** [bem/bem-components-dist#5]
Планируется ли вообще поддерживать в актуальном состоянии данный репо?
Последняя версия bem-components 2.5.1, а тут до сих пор 2.4.0, в котором есть баг с сериализацией чек-боксов. 
В своих проектах использую лишь i-bem.js в связке с bem-components без всех остальных средств БЭМ, поэтому очень удобно было использовать данный репо вместо ручной сборки.

**Comment by tadatuta** [comment]
@AR1ES да, свежие версии опубликую в ближайшее время.

BTW, параллельно версии публикуются на [CDN](https://ru.bem.info/libs/bem-components/v2.4.0/#Подключение-файлов-с-cdn), можно подключать прямо оттуда.

**Comment by tadatuta** [comment]
done
